#!/usr/bin/env node
/**
 * CROSS-LANE COMMIT COORDINATOR
 * 
 * Purpose: Generate commit messages with cross-project coordination metadata
 * 
 * Usage:
 *   node scripts/coordinate-commit.js --lane=2 --message="Brief description"
 *   node scripts/coordinate-commit.js --help
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const COLORS = {
  RESET: '\x1b[0m',
  GREEN: '\x1b[32m',
  YELLOW: '\x1b[33m',
  BLUE: '\x1b[34m',
  CYAN: '\x1b[36m',
  BOLD: '\x1b[1m'
};

// Parse arguments
function parseArgs() {
  const args = {
    lane: null,
    message: null,
    dependsOn: null,
    requiredBy: null,
    artifacts: [],
    help: false
  };

  for (let i = 2; i < process.argv.length; i++) {
    const arg = process.argv[i];
    
    if (arg === '--help' || arg === '-h') {
      args.help = true;
    } else if (arg.startsWith('--lane=')) {
      args.lane = parseInt(arg.split('=')[1]);
    } else if (arg.startsWith('--message=')) {
      args.message = arg.split('=')[1].replace(/^["']|["']$/g, '');
    } else if (arg.startsWith('--depends-on=')) {
      args.dependsOn = arg.split('=')[1];
    } else if (arg.startsWith('--required-by=')) {
      args.requiredBy = arg.split('=')[1];
    } else if (arg.startsWith('--artifact=')) {
      args.artifacts.push(arg.split('=')[1]);
    }
  }

  return args;
}

// Show help
function showHelp() {
  console.log(`
${COLORS.BOLD}CROSS-LANE COMMIT COORDINATOR${COLORS.RESET}

Generates commit messages with cross-project coordination metadata.

${COLORS.BOLD}USAGE${COLORS.RESET}
  node scripts/coordinate-commit.js --lane=X --message="description" [options]

${COLORS.BOLD}OPTIONS${COLORS.RESET}
  --lane=X          Lane number (1=Archivist, 2=SwarmMind, 3=library)
  --message="..."   Brief description of commit
  --depends-on=SHA  Commit this depends on (format: repo/sha)
  --required-by=SHA Commit that requires this (format: repo/sha)
  --artifact=FILE   Files created/modified (can be repeated)
  --help            Show this help

${COLORS.BOLD}EXAMPLES${COLORS.RESET}
  # Simple commit
  node scripts/coordinate-commit.js --lane=2 --message="Add resolver fix"

  # Cross-lane commit
  node scripts/coordinate-commit.js --lane=2 \\
    --message="Fix resolver path" \\
    --depends-on=archivist/abc123 \\
    --artifact=CROSS_PROJECT_REVIEW.md

${COLORS.BOLD}LANES${COLORS.RESET}
  1 = Archivist-Agent (authority: 100)
  2 = SwarmMind (authority: 80)
  3 = self-organizing-library (authority: 60)
`);
}

// Get session info
function getSessionInfo() {
  const sessionPath = 'S:\\Archivist-Agent\\SESSION_REGISTRY.json';
  
  if (!fs.existsSync(sessionPath)) {
    return { sessionId: 'unknown', trustScore: 'unknown' };
  }

  try {
    const registry = JSON.parse(fs.readFileSync(sessionPath, 'utf8'));
    const sessionId = registry.active_sessions?.swarmmind?.session_id || 'unknown';
    const trustScore = registry.coordination_status?.trust_score || 'unknown';
    
    return { sessionId, trustScore };
  } catch (e) {
    return { sessionId: 'unknown', trustScore: 'unknown' };
  }
}

// Get latest commit from another lane
function getLatestCommit(lane) {
  const lanePaths = {
    1: 'S:\\Archivist-Agent',
    2: 'S:\\SwarmMind Self-Optimizing Multi-Agent AI System',
    3: 'S:\\self-organizing-library'
  };

  const lanePath = lanePaths[lane];
  
  if (!lanePath || !fs.existsSync(path.join(lanePath, '.git'))) {
    return 'N/A';
  }

  try {
    const sha = execSync(`git -C "${lanePath}" rev-parse HEAD`, { 
      encoding: 'utf8',
      env: process.env 
    }).trim();
    return sha.substring(0, 7);
  } catch (e) {
    return 'N/A';
  }
}

// Generate commit message
function generateCommitMessage(args) {
  const { sessionId, trustScore } = getSessionInfo();
  const date = new Date().toISOString().split('T')[0];
  
  const laneNames = {
    1: 'archivist-agent',
    2: 'swarmmind',
    3: 'self-organizing-library'
  };

  const laneName = laneNames[args.lane] || 'unknown';
  
  let message = `[LANE-${args.lane}] [SYNC-${date}] ${args.message}

Cross-lane: ${args.dependsOn || args.requiredBy ? 'Yes' : 'No'}
Depends-on: ${args.dependsOn || 'None'}
Required-by: ${args.requiredBy || 'None'}
Session: ${sessionId}
Coordination: ${trustScore}

`;

  if (args.artifacts.length > 0) {
    message += `Artifacts:\n`;
    args.artifacts.forEach(artifact => {
      message += `- ${artifact}\n`;
    });
    message += '\n';
  }

  message += `---

Generated by: coordinate-commit.js
Lane: ${laneName} (authority: ${args.lane === 1 ? 100 : args.lane === 2 ? 80 : 60})
`;

  return message;
}

// Main
function main() {
  const args = parseArgs();

  if (args.help) {
    showHelp();
    process.exit(0);
  }

  if (!args.lane || !args.message) {
    console.error(`${COLORS.YELLOW}Error: --lane and --message are required${COLORS.RESET}`);
    console.error('Run with --help for usage');
    process.exit(1);
  }

  const message = generateCommitMessage(args);

  console.log(`\n${COLORS.BOLD}Generated Commit Message:${COLORS.RESET}\n`);
  console.log(`${COLORS.CYAN}${message}${COLORS.RESET}`);
  console.log(`\n${COLORS.BOLD}To use:${COLORS.RESET}`);
  console.log(`  git commit -F - <<'EOF'\n${message}\nEOF`);
  console.log(`\n${COLORS.BOLD}Or save to file:${COLORS.RESET}`);
  console.log(`  node scripts/coordinate-commit.js --lane=${args.lane} --message="${args.message}" > /tmp/commit-msg.txt`);
  console.log(`  git commit -F /tmp/commit-msg.txt`);
}

main();
